add_test( [==[wordpiece — build_map populates token_to_id]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-wordpiece [==[wordpiece — build_map populates token_to_id]==]  )
set_tests_properties( [==[wordpiece — build_map populates token_to_id]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit wordpiece SKIP_RETURN_CODE 4)
add_test( [==[wordpiece — lookup known token]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-wordpiece [==[wordpiece — lookup known token]==]  )
set_tests_properties( [==[wordpiece — lookup known token]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit wordpiece SKIP_RETURN_CODE 4)
add_test( [==[wordpiece — lookup unknown returns unk_id]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-wordpiece [==[wordpiece — lookup unknown returns unk_id]==]  )
set_tests_properties( [==[wordpiece — lookup unknown returns unk_id]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit wordpiece SKIP_RETURN_CODE 4)
add_test( [==[wordpiece — uncased detection (no 'Hello' in vocab)]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-wordpiece [==[wordpiece — uncased detection (no 'Hello' in vocab)]==]  )
set_tests_properties( [==[wordpiece — uncased detection (no 'Hello' in vocab)]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit wordpiece SKIP_RETURN_CODE 4)
add_test( [==[wordpiece — cased detection ('Hello' in vocab)]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-wordpiece [==[wordpiece — cased detection ('Hello' in vocab)]==]  )
set_tests_properties( [==[wordpiece — cased detection ('Hello' in vocab)]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit wordpiece SKIP_RETURN_CODE 4)
add_test( [==[wordpiece — single known word]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-wordpiece [==[wordpiece — single known word]==]  )
set_tests_properties( [==[wordpiece — single known word]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit wordpiece SKIP_RETURN_CODE 4)
add_test( [==[wordpiece — two words separated by space]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-wordpiece [==[wordpiece — two words separated by space]==]  )
set_tests_properties( [==[wordpiece — two words separated by space]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit wordpiece SKIP_RETURN_CODE 4)
add_test( [==[wordpiece — subword splitting with ## prefix]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-wordpiece [==[wordpiece — subword splitting with ## prefix]==]  )
set_tests_properties( [==[wordpiece — subword splitting with ## prefix]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit wordpiece SKIP_RETURN_CODE 4)
add_test( [==[wordpiece — punctuation splits into own token]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-wordpiece [==[wordpiece — punctuation splits into own token]==]  )
set_tests_properties( [==[wordpiece — punctuation splits into own token]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit wordpiece SKIP_RETURN_CODE 4)
add_test( [==[wordpiece — unknown word produces [UNK]]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-wordpiece [==[wordpiece — unknown word produces \[UNK\]]==]  )
set_tests_properties( [==[wordpiece — unknown word produces [UNK]]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit wordpiece SKIP_RETURN_CODE 4)
add_test( [==[wordpiece — uncased lowering]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-wordpiece [==[wordpiece — uncased lowering]==]  )
set_tests_properties( [==[wordpiece — uncased lowering]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit wordpiece SKIP_RETURN_CODE 4)
add_test( [==[wordpiece — multiple subword splits]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-wordpiece [==[wordpiece — multiple subword splits]==]  )
set_tests_properties( [==[wordpiece — multiple subword splits]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit wordpiece SKIP_RETURN_CODE 4)
add_test( [==[wordpiece — empty input produces empty output]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-wordpiece [==[wordpiece — empty input produces empty output]==]  )
set_tests_properties( [==[wordpiece — empty input produces empty output]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit wordpiece SKIP_RETURN_CODE 4)
add_test( [==[wordpiece — whitespace-only input produces empty output]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-wordpiece [==[wordpiece — whitespace-only input produces empty output]==]  )
set_tests_properties( [==[wordpiece — whitespace-only input produces empty output]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit wordpiece SKIP_RETURN_CODE 4)
add_test( [==[wordpiece — comma splits correctly]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-wordpiece [==[wordpiece — comma splits correctly]==]  )
set_tests_properties( [==[wordpiece — comma splits correctly]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit wordpiece SKIP_RETURN_CODE 4)
set( test-core-wordpiece_TESTS [==[wordpiece — build_map populates token_to_id]==] [==[wordpiece — lookup known token]==] [==[wordpiece — lookup unknown returns unk_id]==] [==[wordpiece — uncased detection (no 'Hello' in vocab)]==] [==[wordpiece — cased detection ('Hello' in vocab)]==] [==[wordpiece — single known word]==] [==[wordpiece — two words separated by space]==] [==[wordpiece — subword splitting with ## prefix]==] [==[wordpiece — punctuation splits into own token]==] [==[wordpiece — unknown word produces [UNK]]==] [==[wordpiece — uncased lowering]==] [==[wordpiece — multiple subword splits]==] [==[wordpiece — empty input produces empty output]==] [==[wordpiece — whitespace-only input produces empty output]==] [==[wordpiece — comma splits correctly]==])
