if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-cosyvoice3-prompt-policy-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-cosyvoice3-prompt-policy-ffb5beb_tests.cmake")
else()
  add_test(test-cosyvoice3-prompt-policy_NOT_BUILT-ffb5beb test-cosyvoice3-prompt-policy_NOT_BUILT-ffb5beb)
endif()
