if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-stream-vad-merge-policy-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-stream-vad-merge-policy-ffb5beb_tests.cmake")
else()
  add_test(test-stream-vad-merge-policy_NOT_BUILT-ffb5beb test-stream-vad-merge-policy_NOT_BUILT-ffb5beb)
endif()
