if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-kokoro-misaki-wiring-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-kokoro-misaki-wiring-ffb5beb_tests.cmake")
else()
  add_test(test-kokoro-misaki-wiring_NOT_BUILT-ffb5beb test-kokoro-misaki-wiring_NOT_BUILT-ffb5beb)
endif()
