if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-orpheussnac-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-orpheussnac-params-ffb5beb_tests.cmake")
else()
  add_test(test-orpheussnac-params_NOT_BUILT-ffb5beb test-orpheussnac-params_NOT_BUILT-ffb5beb)
endif()
