add_test( [==[a reference WAV is a clone, a preset name is not]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-abi-clone-disclosure [==[a reference WAV is a clone\, a preset name is not]==]  )
set_tests_properties( [==[a reference WAV is a clone, a preset name is not]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[the clone warning fires once per session]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-abi-clone-disclosure [==[the clone warning fires once per session]==]  )
set_tests_properties( [==[the clone warning fires once per session]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[attesting silences the clone warning]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-abi-clone-disclosure [==[attesting silences the clone warning]==]  )
set_tests_properties( [==[attesting silences the clone warning]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[non-clone synthesis never warns]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-abi-clone-disclosure [==[non-clone synthesis never warns]==]  )
set_tests_properties( [==[non-clone synthesis never warns]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[get_disclaimer_pcm is refused once a clone voice is set]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-abi-clone-disclosure [==[get_disclaimer_pcm is refused once a clone voice is set]==]  )
set_tests_properties( [==[get_disclaimer_pcm is refused once a clone voice is set]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[the ABI disclosure text matches the CLI's]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-abi-clone-disclosure [==[the ABI disclosure text matches the CLI's]==]  )
set_tests_properties( [==[the ABI disclosure text matches the CLI's]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
set( test-abi-clone-disclosure_TESTS [==[a reference WAV is a clone, a preset name is not]==] [==[the clone warning fires once per session]==] [==[attesting silences the clone warning]==] [==[non-clone synthesis never warns]==] [==[get_disclaimer_pcm is refused once a clone voice is set]==] [==[the ABI disclosure text matches the CLI's]==])
