if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-wyoming-proto-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-wyoming-proto-ffb5beb_tests.cmake")
else()
  add_test(test-wyoming-proto_NOT_BUILT-ffb5beb test-wyoming-proto_NOT_BUILT-ffb5beb)
endif()
