add_test( [==[script-mismatch fires on the #419 shape: ru target, translit output]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-script-mismatch [==[script-mismatch fires on the #419 shape: ru target\, translit output]==]  )
set_tests_properties( [==[script-mismatch fires on the #419 shape: ru target, translit output]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4 LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[script-mismatch stays quiet on correct-script output]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-script-mismatch [==[script-mismatch stays quiet on correct-script output]==]  )
set_tests_properties( [==[script-mismatch stays quiet on correct-script output]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4 LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[script-mismatch tolerates code-switching and short fragments]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-script-mismatch [==[script-mismatch tolerates code-switching and short fragments]==]  )
set_tests_properties( [==[script-mismatch tolerates code-switching and short fragments]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4 LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[script counter handles UTF-8 correctly]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-script-mismatch [==[script counter handles UTF-8 correctly]==]  )
set_tests_properties( [==[script counter handles UTF-8 correctly]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4 LABELS unit SKIP_RETURN_CODE 4)
set( test-script-mismatch_TESTS [==[script-mismatch fires on the #419 shape: ru target, translit output]==] [==[script-mismatch stays quiet on correct-script output]==] [==[script-mismatch tolerates code-switching and short fragments]==] [==[script counter handles UTF-8 correctly]==])
