add_test( [==[to_f32: null tensor returns empty]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-cpu-ops-to-f32 [==[to_f32: null tensor returns empty]==]  )
set_tests_properties( [==[to_f32: null tensor returns empty]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[to_f32: F32 is exact]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-cpu-ops-to-f32 [==[to_f32: F32 is exact]==]  )
set_tests_properties( [==[to_f32: F32 is exact]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[to_f32: F16 within precision]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-cpu-ops-to-f32 [==[to_f32: F16 within precision]==]  )
set_tests_properties( [==[to_f32: F16 within precision]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[to_f32: Q8_0 dequantizes to the original (not garbage)]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-cpu-ops-to-f32 [==[to_f32: Q8_0 dequantizes to the original (not garbage)]==]  )
set_tests_properties( [==[to_f32: Q8_0 dequantizes to the original (not garbage)]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[to_f32: Q4_K dequantizes to the original (not garbage)]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-cpu-ops-to-f32 [==[to_f32: Q4_K dequantizes to the original (not garbage)]==]  )
set_tests_properties( [==[to_f32: Q4_K dequantizes to the original (not garbage)]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
set( test-cpu-ops-to-f32_TESTS [==[to_f32: null tensor returns empty]==] [==[to_f32: F32 is exact]==] [==[to_f32: F16 within precision]==] [==[to_f32: Q8_0 dequantizes to the original (not garbage)]==] [==[to_f32: Q4_K dequantizes to the original (not garbage)]==])
