add_test( [==[clean sequence is not a loop]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-repeat-break [==[clean sequence is not a loop]==]  )
set_tests_properties( [==[clean sequence is not a loop]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit repeat-break moonshine SKIP_RETURN_CODE 4)
add_test( [==[period-1 token repeated >= 4x is a loop]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-repeat-break [==[period-1 token repeated >= 4x is a loop]==]  )
set_tests_properties( [==[period-1 token repeated >= 4x is a loop]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit repeat-break moonshine SKIP_RETURN_CODE 4)
add_test( [==[period-2 block repeated 4x (the moonshine 'I'm sorry' case)]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-repeat-break [==[period-2 block repeated 4x (the moonshine 'I'm sorry' case)]==]  )
set_tests_properties( [==[period-2 block repeated 4x (the moonshine 'I'm sorry' case)]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit repeat-break moonshine SKIP_RETURN_CODE 4)
add_test( [==[period-3 block repeated 4x]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-repeat-break [==[period-3 block repeated 4x]==]  )
set_tests_properties( [==[period-3 block repeated 4x]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit repeat-break moonshine SKIP_RETURN_CODE 4)
add_test( [==[natural short repeat (2x) is not flagged]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-repeat-break [==[natural short repeat (2x) is not flagged]==]  )
set_tests_properties( [==[natural short repeat (2x) is not flagged]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit repeat-break moonshine SKIP_RETURN_CODE 4)
add_test( [==[min_reps / max_period parameters respected]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-repeat-break [==[min_reps / max_period parameters respected]==]  )
set_tests_properties( [==[min_reps / max_period parameters respected]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit repeat-break moonshine SKIP_RETURN_CODE 4)
set( test-repeat-break_TESTS [==[clean sequence is not a loop]==] [==[period-1 token repeated >= 4x is a loop]==] [==[period-2 block repeated 4x (the moonshine 'I'm sorry' case)]==] [==[period-3 block repeated 4x]==] [==[natural short repeat (2x) is not flagged]==] [==[min_reps / max_period parameters respected]==])
