if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test_watermark-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test_watermark-ffb5beb_tests.cmake")
else()
  add_test(test_watermark_NOT_BUILT-ffb5beb test_watermark_NOT_BUILT-ffb5beb)
endif()
