if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-moss-audio-valid-meta-7ddff67_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-moss-audio-valid-meta-7ddff67_tests.cmake")
else()
  add_test(test-moss-audio-valid-meta_NOT_BUILT-7ddff67 test-moss-audio-valid-meta_NOT_BUILT-7ddff67)
endif()
