if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-powerset-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-powerset-ffb5beb_tests.cmake")
else()
  add_test(test-powerset_NOT_BUILT-ffb5beb test-powerset_NOT_BUILT-ffb5beb)
endif()
