if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-tiron-link-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-tiron-link-ffb5beb_tests.cmake")
else()
  add_test(test-tiron-link_NOT_BUILT-ffb5beb test-tiron-link_NOT_BUILT-ffb5beb)
endif()
