if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-moss-tts-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-moss-tts-params-ffb5beb_tests.cmake")
else()
  add_test(test-moss-tts-params_NOT_BUILT-ffb5beb test-moss-tts-params_NOT_BUILT-ffb5beb)
endif()
