if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-gpu-backend-pref-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-gpu-backend-pref-ffb5beb_tests.cmake")
else()
  add_test(test-gpu-backend-pref_NOT_BUILT-ffb5beb test-gpu-backend-pref_NOT_BUILT-ffb5beb)
endif()
