if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-audio-window-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-audio-window-ffb5beb_tests.cmake")
else()
  add_test(test-audio-window_NOT_BUILT-ffb5beb test-audio-window_NOT_BUILT-ffb5beb)
endif()
