if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-diarize-foxnose-turns-live-580e9a9_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-diarize-foxnose-turns-live-580e9a9_tests.cmake")
else()
  add_test(test-diarize-foxnose-turns-live_NOT_BUILT-580e9a9 test-diarize-foxnose-turns-live_NOT_BUILT-580e9a9)
endif()
