if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-voxcpm2-vae-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-voxcpm2-vae-params-ffb5beb_tests.cmake")
else()
  add_test(test-voxcpm2-vae-params_NOT_BUILT-ffb5beb test-voxcpm2-vae-params_NOT_BUILT-ffb5beb)
endif()
