if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-mt3-ed950bc_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-mt3-ed950bc_tests.cmake")
else()
  add_test(test-mt3_NOT_BUILT-ed950bc test-mt3_NOT_BUILT-ed950bc)
endif()
