add_test( [==[WAV header magic bytes]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[WAV header magic bytes]==]  )
set_tests_properties( [==[WAV header magic bytes]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[WAV header field values]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[WAV header field values]==]  )
set_tests_properties( [==[WAV header field values]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[WAV body size matches sample count]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[WAV body size matches sample count]==]  )
set_tests_properties( [==[WAV body size matches sample count]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[WAV serializer clamps samples outside [-1, 1]]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[WAV serializer clamps samples outside \[-1\, 1\]]==]  )
set_tests_properties( [==[WAV serializer clamps samples outside [-1, 1]]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[WAV serializer rounds samples correctly]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[WAV serializer rounds samples correctly]==]  )
set_tests_properties( [==[WAV serializer rounds samples correctly]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[WAV serializer handles boundary values]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[WAV serializer handles boundary values]==]  )
set_tests_properties( [==[WAV serializer handles boundary values]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[WAV serializer accepts varied sample rates]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[WAV serializer accepts varied sample rates]==]  )
set_tests_properties( [==[WAV serializer accepts varied sample rates]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[regression #122: WAV header reflects backend's native rate]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[regression #122: WAV header reflects backend's native rate]==]  )
set_tests_properties( [==[regression #122: WAV header reflects backend's native rate]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[WAV serializer handles empty input]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[WAV serializer handles empty input]==]  )
set_tests_properties( [==[WAV serializer handles empty input]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[WAV total size in RIFF header matches actual byte count]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[WAV total size in RIFF header matches actual byte count]==]  )
set_tests_properties( [==[WAV total size in RIFF header matches actual byte count]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[PCM int16 LE has no header]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[PCM int16 LE has no header]==]  )
set_tests_properties( [==[PCM int16 LE has no header]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[PCM body size = 2 × n_samples]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[PCM body size = 2 × n_samples]==]  )
set_tests_properties( [==[PCM body size = 2 × n_samples]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[PCM applies same clamp as WAV writer]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[PCM applies same clamp as WAV writer]==]  )
set_tests_properties( [==[PCM applies same clamp as WAV writer]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[PCM applies same rounding as WAV writer]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[PCM applies same rounding as WAV writer]==]  )
set_tests_properties( [==[PCM applies same rounding as WAV writer]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[PCM handles empty input]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[PCM handles empty input]==]  )
set_tests_properties( [==[PCM handles empty input]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[WAV contains LIST/INFO chunk with AI provenance]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[WAV contains LIST/INFO chunk with AI provenance]==]  )
set_tests_properties( [==[WAV contains LIST/INFO chunk with AI provenance]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[WAV RIFF size accounts for LIST/INFO chunk]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[WAV RIFF size accounts for LIST/INFO chunk]==]  )
set_tests_properties( [==[WAV RIFF size accounts for LIST/INFO chunk]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[ID3v2 tag structure is valid]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[ID3v2 tag structure is valid]==]  )
set_tests_properties( [==[ID3v2 tag structure is valid]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[PCM byte-stream matches WAV data chunk byte-for-byte]==] /kaggle/working/CrispASR-T4/t4-build/bin/test_server_wav_writer [==[PCM byte-stream matches WAV data chunk byte-for-byte]==]  )
set_tests_properties( [==[PCM byte-stream matches WAV data chunk byte-for-byte]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit SKIP_RETURN_CODE 4)
set( test_server_wav_writer_TESTS [==[WAV header magic bytes]==] [==[WAV header field values]==] [==[WAV body size matches sample count]==] [==[WAV serializer clamps samples outside [-1, 1]]==] [==[WAV serializer rounds samples correctly]==] [==[WAV serializer handles boundary values]==] [==[WAV serializer accepts varied sample rates]==] [==[regression #122: WAV header reflects backend's native rate]==] [==[WAV serializer handles empty input]==] [==[WAV total size in RIFF header matches actual byte count]==] [==[PCM int16 LE has no header]==] [==[PCM body size = 2 × n_samples]==] [==[PCM applies same clamp as WAV writer]==] [==[PCM applies same rounding as WAV writer]==] [==[PCM handles empty input]==] [==[WAV contains LIST/INFO chunk with AI provenance]==] [==[WAV RIFF size accounts for LIST/INFO chunk]==] [==[ID3v2 tag structure is valid]==] [==[PCM byte-stream matches WAV data chunk byte-for-byte]==])
