if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-granitenle-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-granitenle-params-ffb5beb_tests.cmake")
else()
  add_test(test-granitenle-params_NOT_BUILT-ffb5beb test-granitenle-params_NOT_BUILT-ffb5beb)
endif()
