if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-compliance-wiring-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-compliance-wiring-ffb5beb_tests.cmake")
else()
  add_test(test-compliance-wiring_NOT_BUILT-ffb5beb test-compliance-wiring_NOT_BUILT-ffb5beb)
endif()
