if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-session-autochunk-3fc302c_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-session-autochunk-3fc302c_tests.cmake")
else()
  add_test(test-session-autochunk_NOT_BUILT-3fc302c test-session-autochunk_NOT_BUILT-3fc302c)
endif()
