if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-canary-qwen-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-canary-qwen-params-ffb5beb_tests.cmake")
else()
  add_test(test-canary-qwen-params_NOT_BUILT-ffb5beb test-canary-qwen-params_NOT_BUILT-ffb5beb)
endif()
