add_test( [==[bpe — byte_encoder has 256 entries]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — byte_encoder has 256 entries]==]  )
set_tests_properties( [==[bpe — byte_encoder has 256 entries]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[bpe — byte_encoder maps all 256 values to unique codepoints]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — byte_encoder maps all 256 values to unique codepoints]==]  )
set_tests_properties( [==[bpe — byte_encoder maps all 256 values to unique codepoints]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[bpe — printable ASCII bytes map to themselves]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — printable ASCII bytes map to themselves]==]  )
set_tests_properties( [==[bpe — printable ASCII bytes map to themselves]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[bpe — utf8_encode ASCII]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — utf8_encode ASCII]==]  )
set_tests_properties( [==[bpe — utf8_encode ASCII]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[bpe — utf8_encode 2-byte]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — utf8_encode 2-byte]==]  )
set_tests_properties( [==[bpe — utf8_encode 2-byte]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[bpe — utf8_encode 3-byte]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — utf8_encode 3-byte]==]  )
set_tests_properties( [==[bpe — utf8_encode 3-byte]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[bpe — bytes_to_unicode for ASCII printable]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — bytes_to_unicode for ASCII printable]==]  )
set_tests_properties( [==[bpe — bytes_to_unicode for ASCII printable]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[bpe — bytes_to_unicode for null byte]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — bytes_to_unicode for null byte]==]  )
set_tests_properties( [==[bpe — bytes_to_unicode for null byte]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[bpe — byte_decoder inverts byte_encoder]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — byte_decoder inverts byte_encoder]==]  )
set_tests_properties( [==[bpe — byte_decoder inverts byte_encoder]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[bpe — token_bytes_to_utf8 round-trips ASCII]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — token_bytes_to_utf8 round-trips ASCII]==]  )
set_tests_properties( [==[bpe — token_bytes_to_utf8 round-trips ASCII]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[bpe — bpe_one whole-token lookup]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — bpe_one whole-token lookup]==]  )
set_tests_properties( [==[bpe — bpe_one whole-token lookup]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[bpe — bpe_one partial merge]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — bpe_one partial merge]==]  )
set_tests_properties( [==[bpe — bpe_one partial merge]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[bpe — bpe_one no merges (empty merge table)]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — bpe_one no merges (empty merge table)]==]  )
set_tests_properties( [==[bpe — bpe_one no merges (empty merge table)]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[bpe — bpe_one empty input]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — bpe_one empty input]==]  )
set_tests_properties( [==[bpe — bpe_one empty input]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[bpe — Qwen pretokenizer preserves prompt punctuation and newline]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — Qwen pretokenizer preserves prompt punctuation and newline]==]  )
set_tests_properties( [==[bpe — Qwen pretokenizer preserves prompt punctuation and newline]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[bpe — detokenize simple ASCII tokens]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — detokenize simple ASCII tokens]==]  )
set_tests_properties( [==[bpe — detokenize simple ASCII tokens]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[bpe — detokenize skips out-of-range IDs]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[bpe — detokenize skips out-of-range IDs]==]  )
set_tests_properties( [==[bpe — detokenize skips out-of-range IDs]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[spm-bpe — a space becomes U+2581 and changes the result]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[spm-bpe — a space becomes U+2581 and changes the result]==]  )
set_tests_properties( [==[spm-bpe — a space becomes U+2581 and changes the result]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[spm-bpe — merging runs across the whole string, not per word]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[spm-bpe — merging runs across the whole string\, not per word]==]  )
set_tests_properties( [==[spm-bpe — merging runs across the whole string, not per word]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[spm-bpe — merges apply in rank order, not left to right]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[spm-bpe — merges apply in rank order\, not left to right]==]  )
set_tests_properties( [==[spm-bpe — merges apply in rank order, not left to right]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[spm-bpe — unknown symbols fall back per codepoint]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[spm-bpe — unknown symbols fall back per codepoint]==]  )
set_tests_properties( [==[spm-bpe — unknown symbols fall back per codepoint]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[spm-bpe — empty input yields no tokens]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[spm-bpe — empty input yields no tokens]==]  )
set_tests_properties( [==[spm-bpe — empty input yields no tokens]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
add_test( [==[spm-bpe — is NOT interchangeable with tokenize_simple]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-core-bpe [==[spm-bpe — is NOT interchangeable with tokenize_simple]==]  )
set_tests_properties( [==[spm-bpe — is NOT interchangeable with tokenize_simple]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bpe SKIP_RETURN_CODE 4)
set( test-core-bpe_TESTS [==[bpe — byte_encoder has 256 entries]==] [==[bpe — byte_encoder maps all 256 values to unique codepoints]==] [==[bpe — printable ASCII bytes map to themselves]==] [==[bpe — utf8_encode ASCII]==] [==[bpe — utf8_encode 2-byte]==] [==[bpe — utf8_encode 3-byte]==] [==[bpe — bytes_to_unicode for ASCII printable]==] [==[bpe — bytes_to_unicode for null byte]==] [==[bpe — byte_decoder inverts byte_encoder]==] [==[bpe — token_bytes_to_utf8 round-trips ASCII]==] [==[bpe — bpe_one whole-token lookup]==] [==[bpe — bpe_one partial merge]==] [==[bpe — bpe_one no merges (empty merge table)]==] [==[bpe — bpe_one empty input]==] [==[bpe — Qwen pretokenizer preserves prompt punctuation and newline]==] [==[bpe — detokenize simple ASCII tokens]==] [==[bpe — detokenize skips out-of-range IDs]==] [==[spm-bpe — a space becomes U+2581 and changes the result]==] [==[spm-bpe — merging runs across the whole string, not per word]==] [==[spm-bpe — merges apply in rank order, not left to right]==] [==[spm-bpe — unknown symbols fall back per codepoint]==] [==[spm-bpe — empty input yields no tokens]==] [==[spm-bpe — is NOT interchangeable with tokenize_simple]==])
