if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-omnivoice-lang-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-omnivoice-lang-ffb5beb_tests.cmake")
else()
  add_test(test-omnivoice-lang_NOT_BUILT-ffb5beb test-omnivoice-lang_NOT_BUILT-ffb5beb)
endif()
