if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-fastconformer-ctc-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-fastconformer-ctc-params-ffb5beb_tests.cmake")
else()
  add_test(test-fastconformer-ctc-params_NOT_BUILT-ffb5beb test-fastconformer-ctc-params_NOT_BUILT-ffb5beb)
endif()
