if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-realtime-turn-buffer-b12d07c_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-realtime-turn-buffer-b12d07c_tests.cmake")
else()
  add_test(test-realtime-turn-buffer_NOT_BUILT-b12d07c test-realtime-turn-buffer_NOT_BUILT-b12d07c)
endif()
