add_test( [==[bench_enabled — unset env var returns false]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-bench-enabled [==[bench_enabled — unset env var returns false]==]  )
set_tests_properties( [==[bench_enabled — unset env var returns false]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bench SKIP_RETURN_CODE 4)
add_test( [==[bench_enabled — env '1' returns true]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-bench-enabled [==[bench_enabled — env '1' returns true]==]  )
set_tests_properties( [==[bench_enabled — env '1' returns true]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bench SKIP_RETURN_CODE 4)
add_test( [==[bench_enabled — env '0' returns false]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-bench-enabled [==[bench_enabled — env '0' returns false]==]  )
set_tests_properties( [==[bench_enabled — env '0' returns false]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bench SKIP_RETURN_CODE 4)
add_test( [==[bench_enabled — env '' (empty) returns false]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-bench-enabled [==[bench_enabled — env '' (empty) returns false]==]  )
set_tests_properties( [==[bench_enabled — env '' (empty) returns false]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bench SKIP_RETURN_CODE 4)
add_test( [==[bench_enabled — env '42' returns true]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-bench-enabled [==[bench_enabled — env '42' returns true]==]  )
set_tests_properties( [==[bench_enabled — env '42' returns true]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bench SKIP_RETURN_CODE 4)
add_test( [==[bench_enabled — cached value is sticky]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-bench-enabled [==[bench_enabled — cached value is sticky]==]  )
set_tests_properties( [==[bench_enabled — cached value is sticky]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bench SKIP_RETURN_CODE 4)
add_test( [==[bench_stage — RAII timer measures elapsed time]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-bench-enabled [==[bench_stage — RAII timer measures elapsed time]==]  )
set_tests_properties( [==[bench_stage — RAII timer measures elapsed time]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit bench SKIP_RETURN_CODE 4)
set( test-bench-enabled_TESTS [==[bench_enabled — unset env var returns false]==] [==[bench_enabled — env '1' returns true]==] [==[bench_enabled — env '0' returns false]==] [==[bench_enabled — env '' (empty) returns false]==] [==[bench_enabled — env '42' returns true]==] [==[bench_enabled — cached value is sticky]==] [==[bench_stage — RAII timer measures elapsed time]==])
