if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-punc-resolve-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-punc-resolve-ffb5beb_tests.cmake")
else()
  add_test(test-punc-resolve_NOT_BUILT-ffb5beb test-punc-resolve_NOT_BUILT-ffb5beb)
endif()
