if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-tts-ref-cache-3c8b095_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-tts-ref-cache-3c8b095_tests.cmake")
else()
  add_test(test-tts-ref-cache_NOT_BUILT-3c8b095 test-tts-ref-cache_NOT_BUILT-3c8b095)
endif()
