if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-tts-phonemes-policy-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-tts-phonemes-policy-ffb5beb_tests.cmake")
else()
  add_test(test-tts-phonemes-policy_NOT_BUILT-ffb5beb test-tts-phonemes-policy_NOT_BUILT-ffb5beb)
endif()
