if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-flash-attn-defaults-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-flash-attn-defaults-ffb5beb_tests.cmake")
else()
  add_test(test-flash-attn-defaults_NOT_BUILT-ffb5beb test-flash-attn-defaults_NOT_BUILT-ffb5beb)
endif()
