if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-session-setters-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-session-setters-ffb5beb_tests.cmake")
else()
  add_test(test-session-setters_NOT_BUILT-ffb5beb test-session-setters_NOT_BUILT-ffb5beb)
endif()
