if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-confucius4-tts-live-580e9a9_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-confucius4-tts-live-580e9a9_tests.cmake")
else()
  add_test(test-confucius4-tts-live_NOT_BUILT-580e9a9 test-confucius4-tts-live_NOT_BUILT-580e9a9)
endif()
