if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-cohere-lang-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-cohere-lang-ffb5beb_tests.cmake")
else()
  add_test(test-cohere-lang_NOT_BUILT-ffb5beb test-cohere-lang_NOT_BUILT-ffb5beb)
endif()
