add_test( [==[ARPAbet to IPA conversion]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-g2p-en [==[ARPAbet to IPA conversion]==] --colour-mode ansi  )
set_tests_properties( [==[ARPAbet to IPA conversion]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit g2p phonemizer TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[LTS rule-based phonemization]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-g2p-en [==[LTS rule-based phonemization]==] --colour-mode ansi  )
set_tests_properties( [==[LTS rule-based phonemization]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit g2p phonemizer TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[word_to_ipa produces IPA output]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-g2p-en [==[word_to_ipa produces IPA output]==] --colour-mode ansi  )
set_tests_properties( [==[word_to_ipa produces IPA output]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit g2p phonemizer TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[text_to_ipa handles full sentences]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-g2p-en [==[text_to_ipa handles full sentences]==] --colour-mode ansi  )
set_tests_properties( [==[text_to_ipa handles full sentences]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit g2p phonemizer TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[tokenizer splits correctly]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-g2p-en [==[tokenizer splits correctly]==] --colour-mode ansi  )
set_tests_properties( [==[tokenizer splits correctly]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit g2p phonemizer TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[base64 decode]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-g2p-en [==[base64 decode]==] --colour-mode ansi  )
set_tests_properties( [==[base64 decode]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit g2p phonemizer TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[neural G2P JSON loading]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-g2p-en [==[neural G2P JSON loading]==] --colour-mode ansi  )
set_tests_properties( [==[neural G2P JSON loading]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit g2p phonemizer TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[CMUdict file loading]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-g2p-en [==[CMUdict file loading]==] --colour-mode ansi  )
set_tests_properties( [==[CMUdict file loading]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit g2p phonemizer TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[CMUdict IPA output quality]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-g2p-en [==[CMUdict IPA output quality]==] --colour-mode ansi  )
set_tests_properties( [==[CMUdict IPA output quality]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit g2p phonemizer TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[filter_to_inventory strips unmapped chars]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-g2p-en [==[filter_to_inventory strips unmapped chars]==] --colour-mode ansi  )
set_tests_properties( [==[filter_to_inventory strips unmapped chars]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit g2p phonemizer TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[phonemizer builtin_en works without espeak]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-g2p-en [==[phonemizer builtin_en works without espeak]==] --colour-mode ansi  )
set_tests_properties( [==[phonemizer builtin_en works without espeak]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit g2p phonemizer TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[phonemize() cascade works]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-g2p-en [==[phonemize() cascade works]==] --colour-mode ansi  )
set_tests_properties( [==[phonemize() cascade works]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit g2p phonemizer TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[strip espeak language markers]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-g2p-en [==[strip espeak language markers]==] --colour-mode ansi  )
set_tests_properties( [==[strip espeak language markers]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit g2p phonemizer TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[Technical token normalization]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-g2p-en [==[Technical token normalization]==] --colour-mode ansi  )
set_tests_properties( [==[Technical token normalization]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit g2p phonemizer TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[builtin_g2p_language matches the PRIMARY SUBTAG, not a substring]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-g2p-en [==[builtin_g2p_language matches the PRIMARY SUBTAG\, not a substring]==] --colour-mode ansi  )
set_tests_properties( [==[builtin_g2p_language matches the PRIMARY SUBTAG, not a substring]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit g2p phonemizer TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[phonemize_builtin_tts carries punctuation through]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-g2p-en [==[phonemize_builtin_tts carries punctuation through]==] --colour-mode ansi  )
set_tests_properties( [==[phonemize_builtin_tts carries punctuation through]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit g2p phonemizer TIMEOUT 30 SKIP_RETURN_CODE 4)
set( test-g2p-en_TESTS [==[ARPAbet to IPA conversion]==] [==[LTS rule-based phonemization]==] [==[word_to_ipa produces IPA output]==] [==[text_to_ipa handles full sentences]==] [==[tokenizer splits correctly]==] [==[base64 decode]==] [==[neural G2P JSON loading]==] [==[CMUdict file loading]==] [==[CMUdict IPA output quality]==] [==[filter_to_inventory strips unmapped chars]==] [==[phonemizer builtin_en works without espeak]==] [==[phonemize() cascade works]==] [==[strip espeak language markers]==] [==[Technical token normalization]==] [==[builtin_g2p_language matches the PRIMARY SUBTAG, not a substring]==] [==[phonemize_builtin_tts carries punctuation through]==])
