add_test( [==[no offset/duration -> inactive window]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-audio-window [==[no offset/duration -> inactive window]==]  )
set_tests_properties( [==[no offset/duration -> inactive window]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit audio-window SKIP_RETURN_CODE 4)
add_test( [==[offset only -> window from offset to end]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-audio-window [==[offset only -> window from offset to end]==]  )
set_tests_properties( [==[offset only -> window from offset to end]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit audio-window SKIP_RETURN_CODE 4)
add_test( [==[offset + duration -> bounded window]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-audio-window [==[offset + duration -> bounded window]==]  )
set_tests_properties( [==[offset + duration -> bounded window]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit audio-window SKIP_RETURN_CODE 4)
add_test( [==[duration only -> window from start]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-audio-window [==[duration only -> window from start]==]  )
set_tests_properties( [==[duration only -> window from start]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit audio-window SKIP_RETURN_CODE 4)
add_test( [==[duration past end is clamped to the tail]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-audio-window [==[duration past end is clamped to the tail]==]  )
set_tests_properties( [==[duration past end is clamped to the tail]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit audio-window SKIP_RETURN_CODE 4)
add_test( [==[offset at or past end -> past_end]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-audio-window [==[offset at or past end -> past_end]==]  )
set_tests_properties( [==[offset at or past end -> past_end]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit audio-window SKIP_RETURN_CODE 4)
add_test( [==[empty / zero-rate buffer with a window request -> past_end]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-audio-window [==[empty / zero-rate buffer with a window request -> past_end]==]  )
set_tests_properties( [==[empty / zero-rate buffer with a window request -> past_end]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit audio-window SKIP_RETURN_CODE 4)
add_test( [==[trim re-clamps to a shorter channel buffer]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-audio-window [==[trim re-clamps to a shorter channel buffer]==]  )
set_tests_properties( [==[trim re-clamps to a shorter channel buffer]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit audio-window SKIP_RETURN_CODE 4)
add_test( [==[trim on empty vector is safe]==] /kaggle/working/CrispASR-T4/t4-build/bin/test-audio-window [==[trim on empty vector is safe]==]  )
set_tests_properties( [==[trim on empty vector is safe]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-T4/t4-build/tests LABELS unit audio-window SKIP_RETURN_CODE 4)
set( test-audio-window_TESTS [==[no offset/duration -> inactive window]==] [==[offset only -> window from offset to end]==] [==[offset + duration -> bounded window]==] [==[duration only -> window from start]==] [==[duration past end is clamped to the tail]==] [==[offset at or past end -> past_end]==] [==[empty / zero-rate buffer with a window request -> past_end]==] [==[trim re-clamps to a shorter channel buffer]==] [==[trim on empty vector is safe]==])
