if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-segment-hygiene-4a48ad1_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-segment-hygiene-4a48ad1_tests.cmake")
else()
  add_test(test-segment-hygiene_NOT_BUILT-4a48ad1 test-segment-hygiene_NOT_BUILT-4a48ad1)
endif()
