if(EXISTS "/kaggle/working/CrispASR-T4/t4-build/tests/test-nemotron-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-T4/t4-build/tests/test-nemotron-params-ffb5beb_tests.cmake")
else()
  add_test(test-nemotron-params_NOT_BUILT-ffb5beb test-nemotron-params_NOT_BUILT-ffb5beb)
endif()
