if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-session-setters-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-session-setters-ffb5beb_tests.cmake")
else()
  add_test(test-session-setters_NOT_BUILT-ffb5beb test-session-setters_NOT_BUILT-ffb5beb)
endif()
