if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-stream-vad-merge-policy-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-stream-vad-merge-policy-ffb5beb_tests.cmake")
else()
  add_test(test-stream-vad-merge-policy_NOT_BUILT-ffb5beb test-stream-vad-merge-policy_NOT_BUILT-ffb5beb)
endif()
