add_test( [==[norm_text trims and collapses whitespace]==] /content/CrispASR-NB/t4-colab-build/bin/test-asr-parity [==[norm_text trims and collapses whitespace]==]  )
set_tests_properties( [==[norm_text trims and collapses whitespace]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit parity improvements SKIP_RETURN_CODE 4)
add_test( [==[segments_equal: identical lists match]==] /content/CrispASR-NB/t4-colab-build/bin/test-asr-parity [==[segments_equal: identical lists match]==]  )
set_tests_properties( [==[segments_equal: identical lists match]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit parity improvements SKIP_RETURN_CODE 4)
add_test( [==[segments_equal: whitespace-only text diff still matches]==] /content/CrispASR-NB/t4-colab-build/bin/test-asr-parity [==[segments_equal: whitespace-only text diff still matches]==]  )
set_tests_properties( [==[segments_equal: whitespace-only text diff still matches]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit parity improvements SKIP_RETURN_CODE 4)
add_test( [==[segments_equal: case / punctuation diff does NOT match]==] /content/CrispASR-NB/t4-colab-build/bin/test-asr-parity [==[segments_equal: case / punctuation diff does NOT match]==]  )
set_tests_properties( [==[segments_equal: case / punctuation diff does NOT match]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit parity improvements SKIP_RETURN_CODE 4)
add_test( [==[segments_equal: length mismatch fails]==] /content/CrispASR-NB/t4-colab-build/bin/test-asr-parity [==[segments_equal: length mismatch fails]==]  )
set_tests_properties( [==[segments_equal: length mismatch fails]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit parity improvements SKIP_RETURN_CODE 4)
add_test( [==[segments_equal: offset tolerance]==] /content/CrispASR-NB/t4-colab-build/bin/test-asr-parity [==[segments_equal: offset tolerance]==]  )
set_tests_properties( [==[segments_equal: offset tolerance]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit parity improvements SKIP_RETURN_CODE 4)
set( test-asr-parity_TESTS [==[norm_text trims and collapses whitespace]==] [==[segments_equal: identical lists match]==] [==[segments_equal: whitespace-only text diff still matches]==] [==[segments_equal: case / punctuation diff does NOT match]==] [==[segments_equal: length mismatch fails]==] [==[segments_equal: offset tolerance]==])
