if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-chatterbox-text-prep-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-chatterbox-text-prep-ffb5beb_tests.cmake")
else()
  add_test(test-chatterbox-text-prep_NOT_BUILT-ffb5beb test-chatterbox-text-prep_NOT_BUILT-ffb5beb)
endif()
