if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-firered-asr-params-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-firered-asr-params-ffb5beb_tests.cmake")
else()
  add_test(test-firered-asr-params_NOT_BUILT-ffb5beb test-firered-asr-params_NOT_BUILT-ffb5beb)
endif()
