if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-diarize-pyannote-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-diarize-pyannote-ffb5beb_tests.cmake")
else()
  add_test(test-diarize-pyannote_NOT_BUILT-ffb5beb test-diarize-pyannote_NOT_BUILT-ffb5beb)
endif()
