if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-wyoming-proto-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-wyoming-proto-ffb5beb_tests.cmake")
else()
  add_test(test-wyoming-proto_NOT_BUILT-ffb5beb test-wyoming-proto_NOT_BUILT-ffb5beb)
endif()
