if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-miotts-live-ca90f24_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-miotts-live-ca90f24_tests.cmake")
else()
  add_test(test-miotts-live_NOT_BUILT-ca90f24 test-miotts-live_NOT_BUILT-ca90f24)
endif()
