if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-vibevoice-transcript-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-vibevoice-transcript-ffb5beb_tests.cmake")
else()
  add_test(test-vibevoice-transcript_NOT_BUILT-ffb5beb test-vibevoice-transcript_NOT_BUILT-ffb5beb)
endif()
