if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-diarize-smooth-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-diarize-smooth-ffb5beb_tests.cmake")
else()
  add_test(test-diarize-smooth_NOT_BUILT-ffb5beb test-diarize-smooth_NOT_BUILT-ffb5beb)
endif()
