if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-sensevoice-params-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-sensevoice-params-ffb5beb_tests.cmake")
else()
  add_test(test-sensevoice-params_NOT_BUILT-ffb5beb test-sensevoice-params_NOT_BUILT-ffb5beb)
endif()
