if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-powerset-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-powerset-ffb5beb_tests.cmake")
else()
  add_test(test-powerset_NOT_BUILT-ffb5beb test-powerset_NOT_BUILT-ffb5beb)
endif()
