add_test( [==[crispasr_popen: mode 'r' opens a subprocess]==] /content/CrispASR-NB/t4-colab-build/bin/test-issue-239-popen-mode [==[crispasr_popen: mode 'r' opens a subprocess]==]  )
set_tests_properties( [==[crispasr_popen: mode 'r' opens a subprocess]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit popen issue-239 SKIP_RETURN_CODE 4)
add_test( [==[crispasr_popen: mode 'rb' opens a subprocess on all platforms]==] /content/CrispASR-NB/t4-colab-build/bin/test-issue-239-popen-mode [==[crispasr_popen: mode 'rb' opens a subprocess on all platforms]==]  )
set_tests_properties( [==[crispasr_popen: mode 'rb' opens a subprocess on all platforms]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit popen issue-239 SKIP_RETURN_CODE 4)
add_test( [==[crispasr_popen: 'wb' mode strips 'b' cleanly]==] /content/CrispASR-NB/t4-colab-build/bin/test-issue-239-popen-mode [==[crispasr_popen: 'wb' mode strips 'b' cleanly]==]  )
set_tests_properties( [==[crispasr_popen: 'wb' mode strips 'b' cleanly]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit popen issue-239 SKIP_RETURN_CODE 4)
set( test-issue-239-popen-mode_TESTS [==[crispasr_popen: mode 'r' opens a subprocess]==] [==[crispasr_popen: mode 'rb' opens a subprocess on all platforms]==] [==[crispasr_popen: 'wb' mode strips 'b' cleanly]==])
