if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-canary-qwen-live-39bb9b7_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-canary-qwen-live-39bb9b7_tests.cmake")
else()
  add_test(test-canary-qwen-live_NOT_BUILT-39bb9b7 test-canary-qwen-live_NOT_BUILT-39bb9b7)
endif()
