if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-diarize-align-order-a3593ae_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-diarize-align-order-a3593ae_tests.cmake")
else()
  add_test(test-diarize-align-order_NOT_BUILT-a3593ae test-diarize-align-order_NOT_BUILT-a3593ae)
endif()
