add_test( [==[French LTS: ch/ph/gn digraphs]==] /content/CrispASR-NB/t4-colab-build/bin/test-g2p-fr [==[French LTS: ch/ph/gn digraphs]==] --colour-mode ansi  )
set_tests_properties( [==[French LTS: ch/ph/gn digraphs]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit g2p french TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[French LTS: nasal vowels]==] /content/CrispASR-NB/t4-colab-build/bin/test-g2p-fr [==[French LTS: nasal vowels]==] --colour-mode ansi  )
set_tests_properties( [==[French LTS: nasal vowels]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit g2p french TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[French LTS: vowel combinations]==] /content/CrispASR-NB/t4-colab-build/bin/test-g2p-fr [==[French LTS: vowel combinations]==] --colour-mode ansi  )
set_tests_properties( [==[French LTS: vowel combinations]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit g2p french TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[French LTS: silent final consonants]==] /content/CrispASR-NB/t4-colab-build/bin/test-g2p-fr [==[French LTS: silent final consonants]==] --colour-mode ansi  )
set_tests_properties( [==[French LTS: silent final consonants]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit g2p french TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[French LTS: accented vowels]==] /content/CrispASR-NB/t4-colab-build/bin/test-g2p-fr [==[French LTS: accented vowels]==] --colour-mode ansi  )
set_tests_properties( [==[French LTS: accented vowels]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit g2p french TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[French LTS: consonant specifics]==] /content/CrispASR-NB/t4-colab-build/bin/test-g2p-fr [==[French LTS: consonant specifics]==] --colour-mode ansi  )
set_tests_properties( [==[French LTS: consonant specifics]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit g2p french TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[French text_to_ipa]==] /content/CrispASR-NB/t4-colab-build/bin/test-g2p-fr [==[French text_to_ipa]==] --colour-mode ansi  )
set_tests_properties( [==[French text_to_ipa]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit g2p french TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[fr: punctuation is dropped by default, kept on request]==] /content/CrispASR-NB/t4-colab-build/bin/test-g2p-fr [==[fr: punctuation is dropped by default\, kept on request]==] --colour-mode ansi  )
set_tests_properties( [==[fr: punctuation is dropped by default, kept on request]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit g2p french TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[fr: the hyphen is a separator, never a mark]==] /content/CrispASR-NB/t4-colab-build/bin/test-g2p-fr [==[fr: the hyphen is a separator\, never a mark]==] --colour-mode ansi  )
set_tests_properties( [==[fr: the hyphen is a separator, never a mark]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit g2p french TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[fr: a quoted word is looked up without its quotes]==] /content/CrispASR-NB/t4-colab-build/bin/test-g2p-fr [==[fr: a quoted word is looked up without its quotes]==] --colour-mode ansi  )
set_tests_properties( [==[fr: a quoted word is looked up without its quotes]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit g2p french TIMEOUT 30 SKIP_RETURN_CODE 4)
set( test-g2p-fr_TESTS [==[French LTS: ch/ph/gn digraphs]==] [==[French LTS: nasal vowels]==] [==[French LTS: vowel combinations]==] [==[French LTS: silent final consonants]==] [==[French LTS: accented vowels]==] [==[French LTS: consonant specifics]==] [==[French text_to_ipa]==] [==[fr: punctuation is dropped by default, kept on request]==] [==[fr: the hyphen is a separator, never a mark]==] [==[fr: a quoted word is looked up without its quotes]==])
