if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-core-seanet-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-core-seanet-ffb5beb_tests.cmake")
else()
  add_test(test-core-seanet_NOT_BUILT-ffb5beb test-core-seanet_NOT_BUILT-ffb5beb)
endif()
