if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-diarize-pyannote-live-580e9a9_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-diarize-pyannote-live-580e9a9_tests.cmake")
else()
  add_test(test-diarize-pyannote-live_NOT_BUILT-580e9a9 test-diarize-pyannote-live_NOT_BUILT-580e9a9)
endif()
