add_test( [==[tts voice: a new reference is applied]==] /content/CrispASR-NB/t4-colab-build/bin/test-core-tts-voice-policy [==[tts voice: a new reference is applied]==]  )
set_tests_properties( [==[tts voice: a new reference is applied]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[tts voice: an identical repeat is not re-encoded]==] /content/CrispASR-NB/t4-colab-build/bin/test-core-tts-voice-policy [==[tts voice: an identical repeat is not re-encoded]==]  )
set_tests_properties( [==[tts voice: an identical repeat is not re-encoded]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[tts voice: sentinels select the built-in reference]==] /content/CrispASR-NB/t4-colab-build/bin/test-core-tts-voice-policy [==[tts voice: sentinels select the built-in reference]==]  )
set_tests_properties( [==[tts voice: sentinels select the built-in reference]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[tts voice: sentinels are exact, not normalised]==] /content/CrispASR-NB/t4-colab-build/bin/test-core-tts-voice-policy [==[tts voice: sentinels are exact\, not normalised]==]  )
set_tests_properties( [==[tts voice: sentinels are exact, not normalised]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[tts voice: a failed load must not dedupe the retry away]==] /content/CrispASR-NB/t4-colab-build/bin/test-core-tts-voice-policy [==[tts voice: a failed load must not dedupe the retry away]==]  )
set_tests_properties( [==[tts voice: a failed load must not dedupe the retry away]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
set( test-core-tts-voice-policy_TESTS [==[tts voice: a new reference is applied]==] [==[tts voice: an identical repeat is not re-encoded]==] [==[tts voice: sentinels select the built-in reference]==] [==[tts voice: sentinels are exact, not normalised]==] [==[tts voice: a failed load must not dedupe the retry away]==])
