if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test_tts_provenance-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test_tts_provenance-ffb5beb_tests.cmake")
else()
  add_test(test_tts_provenance_NOT_BUILT-ffb5beb test_tts_provenance_NOT_BUILT-ffb5beb)
endif()
