if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-stream-punc-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-stream-punc-ffb5beb_tests.cmake")
else()
  add_test(test-stream-punc_NOT_BUILT-ffb5beb test-stream-punc_NOT_BUILT-ffb5beb)
endif()
