if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-omnivoice-prompt-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-omnivoice-prompt-ffb5beb_tests.cmake")
else()
  add_test(test-omnivoice-prompt_NOT_BUILT-ffb5beb test-omnivoice-prompt_NOT_BUILT-ffb5beb)
endif()
