if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-abi-clone-disclosure-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-abi-clone-disclosure-ffb5beb_tests.cmake")
else()
  add_test(test-abi-clone-disclosure_NOT_BUILT-ffb5beb test-abi-clone-disclosure_NOT_BUILT-ffb5beb)
endif()
