if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-generation-health-c182f0c_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-generation-health-c182f0c_tests.cmake")
else()
  add_test(test-generation-health_NOT_BUILT-c182f0c test-generation-health_NOT_BUILT-c182f0c)
endif()
