if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-separation-io-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-separation-io-ffb5beb_tests.cmake")
else()
  add_test(test-separation-io_NOT_BUILT-ffb5beb test-separation-io_NOT_BUILT-ffb5beb)
endif()
