if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-tts-phonemes-policy-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-tts-phonemes-policy-ffb5beb_tests.cmake")
else()
  add_test(test-tts-phonemes-policy_NOT_BUILT-ffb5beb test-tts-phonemes-policy_NOT_BUILT-ffb5beb)
endif()
