if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-tts-ref-cache-3c8b095_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-tts-ref-cache-3c8b095_tests.cmake")
else()
  add_test(test-tts-ref-cache_NOT_BUILT-3c8b095 test-tts-ref-cache_NOT_BUILT-3c8b095)
endif()
