if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-windows-mic-c23d9dc_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-windows-mic-c23d9dc_tests.cmake")
else()
  add_test(test-windows-mic_NOT_BUILT-c23d9dc test-windows-mic_NOT_BUILT-c23d9dc)
endif()
