if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-speaker-identity-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-speaker-identity-ffb5beb_tests.cmake")
else()
  add_test(test-speaker-identity_NOT_BUILT-ffb5beb test-speaker-identity_NOT_BUILT-ffb5beb)
endif()
