if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-gemma4e2b-params-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-gemma4e2b-params-ffb5beb_tests.cmake")
else()
  add_test(test-gemma4e2b-params_NOT_BUILT-ffb5beb test-gemma4e2b-params_NOT_BUILT-ffb5beb)
endif()
