if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-qwen3-tts-cv-style-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-qwen3-tts-cv-style-ffb5beb_tests.cmake")
else()
  add_test(test-qwen3-tts-cv-style_NOT_BUILT-ffb5beb test-qwen3-tts-cv-style_NOT_BUILT-ffb5beb)
endif()
