if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-marking-policy-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-marking-policy-ffb5beb_tests.cmake")
else()
  add_test(test-marking-policy_NOT_BUILT-ffb5beb test-marking-policy_NOT_BUILT-ffb5beb)
endif()
