if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-no-emotion-recognition-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-no-emotion-recognition-ffb5beb_tests.cmake")
else()
  add_test(test-no-emotion-recognition_NOT_BUILT-ffb5beb test-no-emotion-recognition_NOT_BUILT-ffb5beb)
endif()
