add_test( [==[core_utf8: ascii counts equal byte counts]==] /content/CrispASR-NB/t4-colab-build/bin/test-core-utf8 [==[core_utf8: ascii counts equal byte counts]==]  )
set_tests_properties( [==[core_utf8: ascii counts equal byte counts]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[core_utf8: multi-byte scripts count characters, not bytes]==] /content/CrispASR-NB/t4-colab-build/bin/test-core-utf8 [==[core_utf8: multi-byte scripts count characters\, not bytes]==]  )
set_tests_properties( [==[core_utf8: multi-byte scripts count characters, not bytes]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[core_utf8: mixed scripts add up per codepoint]==] /content/CrispASR-NB/t4-colab-build/bin/test-core-utf8 [==[core_utf8: mixed scripts add up per codepoint]==]  )
set_tests_properties( [==[core_utf8: mixed scripts add up per codepoint]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[core_utf8: degrades on malformed input rather than throwing]==] /content/CrispASR-NB/t4-colab-build/bin/test-core-utf8 [==[core_utf8: degrades on malformed input rather than throwing]==]  )
set_tests_properties( [==[core_utf8: degrades on malformed input rather than throwing]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[core_utf8: empty and null]==] /content/CrispASR-NB/t4-colab-build/bin/test-core-utf8 [==[core_utf8: empty and null]==]  )
set_tests_properties( [==[core_utf8: empty and null]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[core_utf8: agrees with the copies it replaces]==] /content/CrispASR-NB/t4-colab-build/bin/test-core-utf8 [==[core_utf8: agrees with the copies it replaces]==]  )
set_tests_properties( [==[core_utf8: agrees with the copies it replaces]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
set( test-core-utf8_TESTS [==[core_utf8: ascii counts equal byte counts]==] [==[core_utf8: multi-byte scripts count characters, not bytes]==] [==[core_utf8: mixed scripts add up per codepoint]==] [==[core_utf8: degrades on malformed input rather than throwing]==] [==[core_utf8: empty and null]==] [==[core_utf8: agrees with the copies it replaces]==])
