add_test( [==[disabled values resolve to none]==] /content/CrispASR-NB/t4-colab-build/bin/test-punc-resolve [==[disabled values resolve to none]==]  )
set_tests_properties( [==[disabled values resolve to none]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[FireRedPunc aliases map to their GGUFs]==] /content/CrispASR-NB/t4-colab-build/bin/test-punc-resolve [==[FireRedPunc aliases map to their GGUFs]==]  )
set_tests_properties( [==[FireRedPunc aliases map to their GGUFs]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[pcs alias maps to the PCS GGUF]==] /content/CrispASR-NB/t4-colab-build/bin/test-punc-resolve [==[pcs alias maps to the PCS GGUF]==]  )
set_tests_properties( [==[pcs alias maps to the PCS GGUF]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[direct paths are passed through, not downloaded]==] /content/CrispASR-NB/t4-colab-build/bin/test-punc-resolve [==[direct paths are passed through\, not downloaded]==]  )
set_tests_properties( [==[direct paths are passed through, not downloaded]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[a 'pcs' keyword without a .gguf path resolves to none]==] /content/CrispASR-NB/t4-colab-build/bin/test-punc-resolve [==[a 'pcs' keyword without a .gguf path resolves to none]==]  )
set_tests_properties( [==[a 'pcs' keyword without a .gguf path resolves to none]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
set( test-punc-resolve_TESTS [==[disabled values resolve to none]==] [==[FireRedPunc aliases map to their GGUFs]==] [==[pcs alias maps to the PCS GGUF]==] [==[direct paths are passed through, not downloaded]==] [==[a 'pcs' keyword without a .gguf path resolves to none]==])
