if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-chat-close-8a63f63_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-chat-close-8a63f63_tests.cmake")
else()
  add_test(test-chat-close_NOT_BUILT-8a63f63 test-chat-close_NOT_BUILT-8a63f63)
endif()
