add_test( [==[empty trie]==] /content/CrispASR-NB/t4-colab-build/bin/test-context-bias [==[empty trie]==]  )
set_tests_properties( [==[empty trie]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[single hotword insert + match]==] /content/CrispASR-NB/t4-colab-build/bin/test-context-bias [==[single hotword insert + match]==]  )
set_tests_properties( [==[single hotword insert + match]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[multiple hotwords with overlap]==] /content/CrispASR-NB/t4-colab-build/bin/test-context-bias [==[multiple hotwords with overlap]==]  )
set_tests_properties( [==[multiple hotwords with overlap]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[mismatch resets via failure links]==] /content/CrispASR-NB/t4-colab-build/bin/test-context-bias [==[mismatch resets via failure links]==]  )
set_tests_properties( [==[mismatch resets via failure links]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[failure link suffix match]==] /content/CrispASR-NB/t4-colab-build/bin/test-context-bias [==[failure link suffix match]==]  )
set_tests_properties( [==[failure link suffix match]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[parse_hotwords basic]==] /content/CrispASR-NB/t4-colab-build/bin/test-context-bias [==[parse_hotwords basic]==]  )
set_tests_properties( [==[parse_hotwords basic]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[parse_hotwords with boost suffix]==] /content/CrispASR-NB/t4-colab-build/bin/test-context-bias [==[parse_hotwords with boost suffix]==]  )
set_tests_properties( [==[parse_hotwords with boost suffix]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[parse_hotwords empty and whitespace]==] /content/CrispASR-NB/t4-colab-build/bin/test-context-bias [==[parse_hotwords empty and whitespace]==]  )
set_tests_properties( [==[parse_hotwords empty and whitespace]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[build_trie with char tokenizer]==] /content/CrispASR-NB/t4-colab-build/bin/test-context-bias [==[build_trie with char tokenizer]==]  )
set_tests_properties( [==[build_trie with char tokenizer]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[build_trie with boost suffix]==] /content/CrispASR-NB/t4-colab-build/bin/test-context-bias [==[build_trie with boost suffix]==]  )
set_tests_properties( [==[build_trie with boost suffix]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[single-token hotword]==] /content/CrispASR-NB/t4-colab-build/bin/test-context-bias [==[single-token hotword]==]  )
set_tests_properties( [==[single-token hotword]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[token ID out of vocab range ignored]==] /content/CrispASR-NB/t4-colab-build/bin/test-context-bias [==[token ID out of vocab range ignored]==]  )
set_tests_properties( [==[token ID out of vocab range ignored]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[repeated advance and reset]==] /content/CrispASR-NB/t4-colab-build/bin/test-context-bias [==[repeated advance and reset]==]  )
set_tests_properties( [==[repeated advance and reset]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit SKIP_RETURN_CODE 4)
set( test-context-bias_TESTS [==[empty trie]==] [==[single hotword insert + match]==] [==[multiple hotwords with overlap]==] [==[mismatch resets via failure links]==] [==[failure link suffix match]==] [==[parse_hotwords basic]==] [==[parse_hotwords with boost suffix]==] [==[parse_hotwords empty and whitespace]==] [==[build_trie with char tokenizer]==] [==[build_trie with boost suffix]==] [==[single-token hotword]==] [==[token ID out of vocab range ignored]==] [==[repeated advance and reset]==])
