if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-fastconv-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-fastconv-ffb5beb_tests.cmake")
else()
  add_test(test-fastconv_NOT_BUILT-ffb5beb test-fastconv_NOT_BUILT-ffb5beb)
endif()
