if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-kokoro-misaki-wiring-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-kokoro-misaki-wiring-ffb5beb_tests.cmake")
else()
  add_test(test-kokoro-misaki-wiring_NOT_BUILT-ffb5beb test-kokoro-misaki-wiring_NOT_BUILT-ffb5beb)
endif()
