if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-stream-finalize-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-stream-finalize-ffb5beb_tests.cmake")
else()
  add_test(test-stream-finalize_NOT_BUILT-ffb5beb test-stream-finalize_NOT_BUILT-ffb5beb)
endif()
