if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-registry-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-registry-ffb5beb_tests.cmake")
else()
  add_test(test-registry_NOT_BUILT-ffb5beb test-registry_NOT_BUILT-ffb5beb)
endif()
