if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-flash-attn-defaults-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-flash-attn-defaults-ffb5beb_tests.cmake")
else()
  add_test(test-flash-attn-defaults_NOT_BUILT-ffb5beb test-flash-attn-defaults_NOT_BUILT-ffb5beb)
endif()
