add_test( [==[a healthy long recording does not fail over]==] /content/CrispASR-NB/t4-colab-build/bin/test-vad-failover [==[a healthy long recording does not fail over]==]  )
set_tests_properties( [==[a healthy long recording does not fail over]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit vad-failover SKIP_RETURN_CODE 4)
add_test( [==[no speech at all on a long clip fails over]==] /content/CrispASR-NB/t4-colab-build/bin/test-vad-failover [==[no speech at all on a long clip fails over]==]  )
set_tests_properties( [==[no speech at all on a long clip fails over]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit vad-failover SKIP_RETURN_CODE 4)
add_test( [==[a trace of speech on a long clip fails over]==] /content/CrispASR-NB/t4-colab-build/bin/test-vad-failover [==[a trace of speech on a long clip fails over]==]  )
set_tests_properties( [==[a trace of speech on a long clip fails over]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit vad-failover SKIP_RETURN_CODE 4)
add_test( [==[short clips never fail over]==] /content/CrispASR-NB/t4-colab-build/bin/test-vad-failover [==[short clips never fail over]==]  )
set_tests_properties( [==[short clips never fail over]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit vad-failover SKIP_RETURN_CODE 4)
add_test( [==[a long CONTINUOUS monologue is not mistaken for a failure]==] /content/CrispASR-NB/t4-colab-build/bin/test-vad-failover [==[a long CONTINUOUS monologue is not mistaken for a failure]==]  )
set_tests_properties( [==[a long CONTINUOUS monologue is not mistaken for a failure]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit vad-failover SKIP_RETURN_CODE 4)
add_test( [==[few segments AND low coverage on a very long clip fails over]==] /content/CrispASR-NB/t4-colab-build/bin/test-vad-failover [==[few segments AND low coverage on a very long clip fails over]==]  )
set_tests_properties( [==[few segments AND low coverage on a very long clip fails over]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit vad-failover SKIP_RETURN_CODE 4)
add_test( [==[sparse-but-real speech on a long clip is preserved]==] /content/CrispASR-NB/t4-colab-build/bin/test-vad-failover [==[sparse-but-real speech on a long clip is preserved]==]  )
set_tests_properties( [==[sparse-but-real speech on a long clip is preserved]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit vad-failover SKIP_RETURN_CODE 4)
add_test( [==[unknown duration never fails over]==] /content/CrispASR-NB/t4-colab-build/bin/test-vad-failover [==[unknown duration never fails over]==]  )
set_tests_properties( [==[unknown duration never fails over]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit vad-failover SKIP_RETURN_CODE 4)
add_test( [==[degenerate spans do not inflate coverage]==] /content/CrispASR-NB/t4-colab-build/bin/test-vad-failover [==[degenerate spans do not inflate coverage]==]  )
set_tests_properties( [==[degenerate spans do not inflate coverage]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit vad-failover SKIP_RETURN_CODE 4)
add_test( [==[thresholds are configurable]==] /content/CrispASR-NB/t4-colab-build/bin/test-vad-failover [==[thresholds are configurable]==]  )
set_tests_properties( [==[thresholds are configurable]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit vad-failover SKIP_RETURN_CODE 4)
set( test-vad-failover_TESTS [==[a healthy long recording does not fail over]==] [==[no speech at all on a long clip fails over]==] [==[a trace of speech on a long clip fails over]==] [==[short clips never fail over]==] [==[a long CONTINUOUS monologue is not mistaken for a failure]==] [==[few segments AND low coverage on a very long clip fails over]==] [==[sparse-but-real speech on a long clip is preserved]==] [==[unknown duration never fails over]==] [==[degenerate spans do not inflate coverage]==] [==[thresholds are configurable]==])
