add_test( [==[ref cache: what the CLI writes, the session reads]==] /content/CrispASR-NB/t4-colab-build/bin/test-tts-ref-cache [==[ref cache: what the CLI writes\, the session reads]==]  )
set_tests_properties( [==[ref cache: what the CLI writes, the session reads]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit tts SKIP_RETURN_CODE 4)
add_test( [==[ref cache: a mismatched tag is rejected, not misread]==] /content/CrispASR-NB/t4-colab-build/bin/test-tts-ref-cache [==[ref cache: a mismatched tag is rejected\, not misread]==]  )
set_tests_properties( [==[ref cache: a mismatched tag is rejected, not misread]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit tts SKIP_RETURN_CODE 4)
add_test( [==[ref cache: absent cache reports absent]==] /content/CrispASR-NB/t4-colab-build/bin/test-tts-ref-cache [==[ref cache: absent cache reports absent]==]  )
set_tests_properties( [==[ref cache: absent cache reports absent]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit tts SKIP_RETURN_CODE 4)
add_test( [==[ref cache: an edited clip invalidates its transcript]==] /content/CrispASR-NB/t4-colab-build/bin/test-tts-ref-cache [==[ref cache: an edited clip invalidates its transcript]==]  )
set_tests_properties( [==[ref cache: an edited clip invalidates its transcript]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit tts SKIP_RETURN_CODE 4)
add_test( [==[ref cache: the cache path sits beside the clip]==] /content/CrispASR-NB/t4-colab-build/bin/test-tts-ref-cache [==[ref cache: the cache path sits beside the clip]==]  )
set_tests_properties( [==[ref cache: the cache path sits beside the clip]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit tts SKIP_RETURN_CODE 4)
add_test( [==[ref cache: both layers share one suffix constant]==] /content/CrispASR-NB/t4-colab-build/bin/test-tts-ref-cache [==[ref cache: both layers share one suffix constant]==]  )
set_tests_properties( [==[ref cache: both layers share one suffix constant]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit tts SKIP_RETURN_CODE 4)
set( test-tts-ref-cache_TESTS [==[ref cache: what the CLI writes, the session reads]==] [==[ref cache: a mismatched tag is rejected, not misread]==] [==[ref cache: absent cache reports absent]==] [==[ref cache: an edited clip invalidates its transcript]==] [==[ref cache: the cache path sits beside the clip]==] [==[ref cache: both layers share one suffix constant]==])
