if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-core-bpe-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-core-bpe-ffb5beb_tests.cmake")
else()
  add_test(test-core-bpe_NOT_BUILT-ffb5beb test-core-bpe_NOT_BUILT-ffb5beb)
endif()
