if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-crispasr-cache-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-crispasr-cache-ffb5beb_tests.cmake")
else()
  add_test(test-crispasr-cache_NOT_BUILT-ffb5beb test-crispasr-cache_NOT_BUILT-ffb5beb)
endif()
