if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-punctuation-policy-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-punctuation-policy-ffb5beb_tests.cmake")
else()
  add_test(test-punctuation-policy_NOT_BUILT-ffb5beb test-punctuation-policy_NOT_BUILT-ffb5beb)
endif()
