if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-step-graph-cache-66f53cb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-step-graph-cache-66f53cb_tests.cmake")
else()
  add_test(test-step-graph-cache_NOT_BUILT-66f53cb test-step-graph-cache_NOT_BUILT-66f53cb)
endif()
