if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-m2m100-params-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-m2m100-params-ffb5beb_tests.cmake")
else()
  add_test(test-m2m100-params_NOT_BUILT-ffb5beb test-m2m100-params_NOT_BUILT-ffb5beb)
endif()
