if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test_c2pa_native-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test_c2pa_native-ffb5beb_tests.cmake")
else()
  add_test(test_c2pa_native_NOT_BUILT-ffb5beb test_c2pa_native_NOT_BUILT-ffb5beb)
endif()
