if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-compliance-wiring-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-compliance-wiring-ffb5beb_tests.cmake")
else()
  add_test(test-compliance-wiring_NOT_BUILT-ffb5beb test-compliance-wiring_NOT_BUILT-ffb5beb)
endif()
