if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-funasr-params-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-funasr-params-ffb5beb_tests.cmake")
else()
  add_test(test-funasr-params_NOT_BUILT-ffb5beb test-funasr-params_NOT_BUILT-ffb5beb)
endif()
