if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-asr-overlap-trim-057fd5f_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-asr-overlap-trim-057fd5f_tests.cmake")
else()
  add_test(test-asr-overlap-trim_NOT_BUILT-057fd5f test-asr-overlap-trim_NOT_BUILT-057fd5f)
endif()
