if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-issue-239-popen-mode-4babfaf_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-issue-239-popen-mode-4babfaf_tests.cmake")
else()
  add_test(test-issue-239-popen-mode_NOT_BUILT-4babfaf test-issue-239-popen-mode_NOT_BUILT-4babfaf)
endif()
