if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-crispasr-speaker-resample-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-crispasr-speaker-resample-ffb5beb_tests.cmake")
else()
  add_test(test-crispasr-speaker-resample_NOT_BUILT-ffb5beb test-crispasr-speaker-resample_NOT_BUILT-ffb5beb)
endif()
