if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-gpu-backend-pref-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-gpu-backend-pref-ffb5beb_tests.cmake")
else()
  add_test(test-gpu-backend-pref_NOT_BUILT-ffb5beb test-gpu-backend-pref_NOT_BUILT-ffb5beb)
endif()
