if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-tiron-link-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-tiron-link-ffb5beb_tests.cmake")
else()
  add_test(test-tiron-link_NOT_BUILT-ffb5beb test-tiron-link_NOT_BUILT-ffb5beb)
endif()
