if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-canary-qwen-params-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-canary-qwen-params-ffb5beb_tests.cmake")
else()
  add_test(test-canary-qwen-params_NOT_BUILT-ffb5beb test-canary-qwen-params_NOT_BUILT-ffb5beb)
endif()
