if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-zonos-params-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-zonos-params-ffb5beb_tests.cmake")
else()
  add_test(test-zonos-params_NOT_BUILT-ffb5beb test-zonos-params_NOT_BUILT-ffb5beb)
endif()
