if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-voxtral4b-params-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-voxtral4b-params-ffb5beb_tests.cmake")
else()
  add_test(test-voxtral4b-params_NOT_BUILT-ffb5beb test-voxtral4b-params_NOT_BUILT-ffb5beb)
endif()
