if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-copies-in-sync-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-copies-in-sync-ffb5beb_tests.cmake")
else()
  add_test(test-copies-in-sync_NOT_BUILT-ffb5beb test-copies-in-sync_NOT_BUILT-ffb5beb)
endif()
