if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-gguf-mapping-released-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-gguf-mapping-released-ffb5beb_tests.cmake")
else()
  add_test(test-gguf-mapping-released_NOT_BUILT-ffb5beb test-gguf-mapping-released_NOT_BUILT-ffb5beb)
endif()
