if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-glint-simd-detect-33bc88f_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-glint-simd-detect-33bc88f_tests.cmake")
else()
  add_test(test-glint-simd-detect_NOT_BUILT-33bc88f test-glint-simd-detect_NOT_BUILT-33bc88f)
endif()
