if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-espeak-phonemize-6a7d21a_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-espeak-phonemize-6a7d21a_tests.cmake")
else()
  add_test(test-espeak-phonemize_NOT_BUILT-6a7d21a test-espeak-phonemize_NOT_BUILT-6a7d21a)
endif()
