if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-link-odr-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-link-odr-ffb5beb_tests.cmake")
else()
  add_test(test-link-odr_NOT_BUILT-ffb5beb test-link-odr_NOT_BUILT-ffb5beb)
endif()
