if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test_audioseal-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test_audioseal-ffb5beb_tests.cmake")
else()
  add_test(test_audioseal_NOT_BUILT-ffb5beb test_audioseal_NOT_BUILT-ffb5beb)
endif()
