if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-cosyvoice3-prompt-policy-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-cosyvoice3-prompt-policy-ffb5beb_tests.cmake")
else()
  add_test(test-cosyvoice3-prompt-policy_NOT_BUILT-ffb5beb test-cosyvoice3-prompt-policy_NOT_BUILT-ffb5beb)
endif()
