if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-parakeet-params-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-parakeet-params-ffb5beb_tests.cmake")
else()
  add_test(test-parakeet-params_NOT_BUILT-ffb5beb test-parakeet-params_NOT_BUILT-ffb5beb)
endif()
