if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-lid-speech-prefix-4f4de72_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-lid-speech-prefix-4f4de72_tests.cmake")
else()
  add_test(test-lid-speech-prefix_NOT_BUILT-4f4de72 test-lid-speech-prefix_NOT_BUILT-4f4de72)
endif()
