if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-bench-enabled-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-bench-enabled-ffb5beb_tests.cmake")
else()
  add_test(test-bench-enabled_NOT_BUILT-ffb5beb test-bench-enabled_NOT_BUILT-ffb5beb)
endif()
