if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-audio-window-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-audio-window-ffb5beb_tests.cmake")
else()
  add_test(test-audio-window_NOT_BUILT-ffb5beb test-audio-window_NOT_BUILT-ffb5beb)
endif()
