if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test_vibevoice_wav_ref-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test_vibevoice_wav_ref-ffb5beb_tests.cmake")
else()
  add_test(test_vibevoice_wav_ref_NOT_BUILT-ffb5beb test_vibevoice_wav_ref_NOT_BUILT-ffb5beb)
endif()
