if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-companion-resolve-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-companion-resolve-ffb5beb_tests.cmake")
else()
  add_test(test-companion-resolve_NOT_BUILT-ffb5beb test-companion-resolve_NOT_BUILT-ffb5beb)
endif()
