if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-embed-parallel-d714a8a_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-embed-parallel-d714a8a_tests.cmake")
else()
  add_test(test-embed-parallel_NOT_BUILT-d714a8a test-embed-parallel_NOT_BUILT-d714a8a)
endif()
