if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-cpu-ops-to-f32-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-cpu-ops-to-f32-ffb5beb_tests.cmake")
else()
  add_test(test-cpu-ops-to-f32_NOT_BUILT-ffb5beb test-cpu-ops-to-f32_NOT_BUILT-ffb5beb)
endif()
