if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-audio-formats-d4ac18e_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-audio-formats-d4ac18e_tests.cmake")
else()
  add_test(test-audio-formats_NOT_BUILT-d4ac18e test-audio-formats_NOT_BUILT-d4ac18e)
endif()
