if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test_watermark-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test_watermark-ffb5beb_tests.cmake")
else()
  add_test(test_watermark_NOT_BUILT-ffb5beb test_watermark_NOT_BUILT-ffb5beb)
endif()
