add_test( [==[gen-health: non-empty text passes]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: non-empty text passes]==]  )
set_tests_properties( [==[gen-health: non-empty text passes]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: empty string fails]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: empty string fails]==]  )
set_tests_properties( [==[gen-health: empty string fails]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: null fails]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: null fails]==]  )
set_tests_properties( [==[gen-health: null fails]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: whitespace-only fails]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: whitespace-only fails]==]  )
set_tests_properties( [==[gen-health: whitespace-only fails]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: plausible duration passes]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: plausible duration passes]==]  )
set_tests_properties( [==[gen-health: plausible duration passes]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: too-short transcript fails]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: too-short transcript fails]==]  )
set_tests_properties( [==[gen-health: too-short transcript fails]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: too-long transcript fails]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: too-long transcript fails]==]  )
set_tests_properties( [==[gen-health: too-long transcript fails]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: normal text has no loop]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: normal text has no loop]==]  )
set_tests_properties( [==[gen-health: normal text has no loop]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: repeated word triggers loop]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: repeated word triggers loop]==]  )
set_tests_properties( [==[gen-health: repeated word triggers loop]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: short repetition is OK]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: short repetition is OK]==]  )
set_tests_properties( [==[gen-health: short repetition is OK]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: custom repeat threshold]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: custom repeat threshold]==]  )
set_tests_properties( [==[gen-health: custom repeat threshold]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: within max_tokens passes]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: within max_tokens passes]==]  )
set_tests_properties( [==[gen-health: within max_tokens passes]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: at max_tokens fails]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: at max_tokens fails]==]  )
set_tests_properties( [==[gen-health: at max_tokens fails]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: plausible TTS duration passes]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: plausible TTS duration passes]==]  )
set_tests_properties( [==[gen-health: plausible TTS duration passes]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: TTS too short fails]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: TTS too short fails]==]  )
set_tests_properties( [==[gen-health: TTS too short fails]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: TTS too long fails]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: TTS too long fails]==]  )
set_tests_properties( [==[gen-health: TTS too long fails]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: short trailing silence passes]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: short trailing silence passes]==]  )
set_tests_properties( [==[gen-health: short trailing silence passes]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: long trailing silence fails]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: long trailing silence fails]==]  )
set_tests_properties( [==[gen-health: long trailing silence fails]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: all-silence audio fails trailing-silence]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: all-silence audio fails trailing-silence]==]  )
set_tests_properties( [==[gen-health: all-silence audio fails trailing-silence]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: trailing-silence null/zero is skipped]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: trailing-silence null/zero is skipped]==]  )
set_tests_properties( [==[gen-health: trailing-silence null/zero is skipped]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: French transcript plausible duration passes]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: French transcript plausible duration passes]==]  )
set_tests_properties( [==[gen-health: French transcript plausible duration passes]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: German compound-word transcript passes]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: German compound-word transcript passes]==]  )
set_tests_properties( [==[gen-health: German compound-word transcript passes]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: accented repeated word triggers loop (UTF-8)]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: accented repeated word triggers loop (UTF-8)]==]  )
set_tests_properties( [==[gen-health: accented repeated word triggers loop (UTF-8)]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: German repeated word triggers loop]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: German repeated word triggers loop]==]  )
set_tests_properties( [==[gen-health: German repeated word triggers loop]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
add_test( [==[gen-health: mixed-language normal text has no loop]==] /content/CrispASR-NB/t4-colab-build/bin/test-generation-health [==[gen-health: mixed-language normal text has no loop]==]  )
set_tests_properties( [==[gen-health: mixed-language normal text has no loop]==] PROPERTIES WORKING_DIRECTORY /content/CrispASR-NB/t4-colab-build/tests LABELS unit gen-health SKIP_RETURN_CODE 4)
set( test-generation-health_TESTS [==[gen-health: non-empty text passes]==] [==[gen-health: empty string fails]==] [==[gen-health: null fails]==] [==[gen-health: whitespace-only fails]==] [==[gen-health: plausible duration passes]==] [==[gen-health: too-short transcript fails]==] [==[gen-health: too-long transcript fails]==] [==[gen-health: normal text has no loop]==] [==[gen-health: repeated word triggers loop]==] [==[gen-health: short repetition is OK]==] [==[gen-health: custom repeat threshold]==] [==[gen-health: within max_tokens passes]==] [==[gen-health: at max_tokens fails]==] [==[gen-health: plausible TTS duration passes]==] [==[gen-health: TTS too short fails]==] [==[gen-health: TTS too long fails]==] [==[gen-health: short trailing silence passes]==] [==[gen-health: long trailing silence fails]==] [==[gen-health: all-silence audio fails trailing-silence]==] [==[gen-health: trailing-silence null/zero is skipped]==] [==[gen-health: French transcript plausible duration passes]==] [==[gen-health: German compound-word transcript passes]==] [==[gen-health: accented repeated word triggers loop (UTF-8)]==] [==[gen-health: German repeated word triggers loop]==] [==[gen-health: mixed-language normal text has no loop]==])
