if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-script-mismatch-95f221c_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-script-mismatch-95f221c_tests.cmake")
else()
  add_test(test-script-mismatch_NOT_BUILT-95f221c test-script-mismatch_NOT_BUILT-95f221c)
endif()
