if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-lcs-c-abi-4380d61_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-lcs-c-abi-4380d61_tests.cmake")
else()
  add_test(test-lcs-c-abi_NOT_BUILT-4380d61 test-lcs-c-abi_NOT_BUILT-4380d61)
endif()
