if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-session-beam-fe92e35_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-session-beam-fe92e35_tests.cmake")
else()
  add_test(test-session-beam_NOT_BUILT-fe92e35 test-session-beam_NOT_BUILT-fe92e35)
endif()
