if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-moonshine-streaming-params-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-moonshine-streaming-params-ffb5beb_tests.cmake")
else()
  add_test(test-moonshine-streaming-params_NOT_BUILT-ffb5beb test-moonshine-streaming-params_NOT_BUILT-ffb5beb)
endif()
