if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-whisper-special-tokens-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-whisper-special-tokens-ffb5beb_tests.cmake")
else()
  add_test(test-whisper-special-tokens_NOT_BUILT-ffb5beb test-whisper-special-tokens_NOT_BUILT-ffb5beb)
endif()
