if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-voice-clone-policy-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-voice-clone-policy-ffb5beb_tests.cmake")
else()
  add_test(test-voice-clone-policy_NOT_BUILT-ffb5beb test-voice-clone-policy_NOT_BUILT-ffb5beb)
endif()
