if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-pockettts-params-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-pockettts-params-ffb5beb_tests.cmake")
else()
  add_test(test-pockettts-params_NOT_BUILT-ffb5beb test-pockettts-params_NOT_BUILT-ffb5beb)
endif()
