if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-wav2vec2-params-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-wav2vec2-params-ffb5beb_tests.cmake")
else()
  add_test(test-wav2vec2-params_NOT_BUILT-ffb5beb test-wav2vec2-params_NOT_BUILT-ffb5beb)
endif()
