if(EXISTS "/content/CrispASR-NB/t4-colab-build/tests/test-cohere-lang-gguf-ffb5beb_tests.cmake")
  include("/content/CrispASR-NB/t4-colab-build/tests/test-cohere-lang-gguf-ffb5beb_tests.cmake")
else()
  add_test(test-cohere-lang-gguf_NOT_BUILT-ffb5beb test-cohere-lang-gguf_NOT_BUILT-ffb5beb)
endif()
