if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-speaker-identity-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-speaker-identity-ffb5beb_tests.cmake")
else()
  add_test(test-speaker-identity_NOT_BUILT-ffb5beb test-speaker-identity_NOT_BUILT-ffb5beb)
endif()
