if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-audio-resample-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-audio-resample-ffb5beb_tests.cmake")
else()
  add_test(test-audio-resample_NOT_BUILT-ffb5beb test-audio-resample_NOT_BUILT-ffb5beb)
endif()
