if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-abi-clone-disclosure-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-abi-clone-disclosure-ffb5beb_tests.cmake")
else()
  add_test(test-abi-clone-disclosure_NOT_BUILT-ffb5beb test-abi-clone-disclosure_NOT_BUILT-ffb5beb)
endif()
