if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-session-abi-nulls-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-session-abi-nulls-ffb5beb_tests.cmake")
else()
  add_test(test-session-abi-nulls_NOT_BUILT-ffb5beb test-session-abi-nulls_NOT_BUILT-ffb5beb)
endif()
