if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-marking-policy-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-marking-policy-ffb5beb_tests.cmake")
else()
  add_test(test-marking-policy_NOT_BUILT-ffb5beb test-marking-policy_NOT_BUILT-ffb5beb)
endif()
