if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-repeat-break-881bda5_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-repeat-break-881bda5_tests.cmake")
else()
  add_test(test-repeat-break_NOT_BUILT-881bda5 test-repeat-break_NOT_BUILT-881bda5)
endif()
