if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-t5translate-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-t5translate-params-ffb5beb_tests.cmake")
else()
  add_test(test-t5translate-params_NOT_BUILT-ffb5beb test-t5translate-params_NOT_BUILT-ffb5beb)
endif()
