if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-firered-asr-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-firered-asr-params-ffb5beb_tests.cmake")
else()
  add_test(test-firered-asr-params_NOT_BUILT-ffb5beb test-firered-asr-params_NOT_BUILT-ffb5beb)
endif()
