if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-parlertts-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-parlertts-params-ffb5beb_tests.cmake")
else()
  add_test(test-parlertts-params_NOT_BUILT-ffb5beb test-parlertts-params_NOT_BUILT-ffb5beb)
endif()
