if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-separation-io-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-separation-io-ffb5beb_tests.cmake")
else()
  add_test(test-separation-io_NOT_BUILT-ffb5beb test-separation-io_NOT_BUILT-ffb5beb)
endif()
