if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-gemma4e2b-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-gemma4e2b-params-ffb5beb_tests.cmake")
else()
  add_test(test-gemma4e2b-params_NOT_BUILT-ffb5beb test-gemma4e2b-params_NOT_BUILT-ffb5beb)
endif()
