if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-outetts-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-outetts-params-ffb5beb_tests.cmake")
else()
  add_test(test-outetts-params_NOT_BUILT-ffb5beb test-outetts-params_NOT_BUILT-ffb5beb)
endif()
