if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-gguf-split-alloc-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-gguf-split-alloc-ffb5beb_tests.cmake")
else()
  add_test(test-gguf-split-alloc_NOT_BUILT-ffb5beb test-gguf-split-alloc_NOT_BUILT-ffb5beb)
endif()
