if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-cohere-lang-gguf-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-cohere-lang-gguf-ffb5beb_tests.cmake")
else()
  add_test(test-cohere-lang-gguf_NOT_BUILT-ffb5beb test-cohere-lang-gguf_NOT_BUILT-ffb5beb)
endif()
