if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-f5tts-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-f5tts-params-ffb5beb_tests.cmake")
else()
  add_test(test-f5tts-params_NOT_BUILT-ffb5beb test-f5tts-params_NOT_BUILT-ffb5beb)
endif()
