if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-melotts-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-melotts-params-ffb5beb_tests.cmake")
else()
  add_test(test-melotts-params_NOT_BUILT-ffb5beb test-melotts-params_NOT_BUILT-ffb5beb)
endif()
