if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-pinyin-g2p-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-pinyin-g2p-ffb5beb_tests.cmake")
else()
  add_test(test-pinyin-g2p_NOT_BUILT-ffb5beb test-pinyin-g2p_NOT_BUILT-ffb5beb)
endif()
