if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-align-only-50e47dc_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-align-only-50e47dc_tests.cmake")
else()
  add_test(test-align-only_NOT_BUILT-50e47dc test-align-only_NOT_BUILT-50e47dc)
endif()
