if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-csm-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-csm-params-ffb5beb_tests.cmake")
else()
  add_test(test-csm-params_NOT_BUILT-ffb5beb test-csm-params_NOT_BUILT-ffb5beb)
endif()
