if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-fastconv-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-fastconv-ffb5beb_tests.cmake")
else()
  add_test(test-fastconv_NOT_BUILT-ffb5beb test-fastconv_NOT_BUILT-ffb5beb)
endif()
