if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test_c2pa_native-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test_c2pa_native-ffb5beb_tests.cmake")
else()
  add_test(test_c2pa_native_NOT_BUILT-ffb5beb test_c2pa_native_NOT_BUILT-ffb5beb)
endif()
