if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-diarize-smooth-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-diarize-smooth-ffb5beb_tests.cmake")
else()
  add_test(test-diarize-smooth_NOT_BUILT-ffb5beb test-diarize-smooth_NOT_BUILT-ffb5beb)
endif()
