if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-lcs-chunk-merge-1c3c7ff_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-lcs-chunk-merge-1c3c7ff_tests.cmake")
else()
  add_test(test-lcs-chunk-merge_NOT_BUILT-1c3c7ff test-lcs-chunk-merge_NOT_BUILT-1c3c7ff)
endif()
