if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-registry-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-registry-ffb5beb_tests.cmake")
else()
  add_test(test-registry_NOT_BUILT-ffb5beb test-registry_NOT_BUILT-ffb5beb)
endif()
