if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-asr-sensitivity-bba9eb2_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-asr-sensitivity-bba9eb2_tests.cmake")
else()
  add_test(test-asr-sensitivity_NOT_BUILT-bba9eb2 test-asr-sensitivity_NOT_BUILT-bba9eb2)
endif()
