if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-stream-vad-skip-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-stream-vad-skip-ffb5beb_tests.cmake")
else()
  add_test(test-stream-vad-skip_NOT_BUILT-ffb5beb test-stream-vad-skip_NOT_BUILT-ffb5beb)
endif()
