if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-btc-vocab-7539699_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-btc-vocab-7539699_tests.cmake")
else()
  add_test(test-btc-vocab_NOT_BUILT-7539699 test-btc-vocab_NOT_BUILT-7539699)
endif()
