if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-der-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-der-ffb5beb_tests.cmake")
else()
  add_test(test-der_NOT_BUILT-ffb5beb test-der_NOT_BUILT-ffb5beb)
endif()
