if(EXISTS "/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-htdemucs-gates-95fe88f_tests.cmake")
  include("/kaggle/working/CrispASR/cpu-kaggle-build/tests/test-htdemucs-gates-95fe88f_tests.cmake")
else()
  add_test(test-htdemucs-gates_NOT_BUILT-95fe88f test-htdemucs-gates_NOT_BUILT-95fe88f)
endif()
