if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-chatterbox-text-prep-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-chatterbox-text-prep-ffb5beb_tests.cmake")
else()
  add_test(test-chatterbox-text-prep_NOT_BUILT-ffb5beb test-chatterbox-text-prep_NOT_BUILT-ffb5beb)
endif()
