if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-companion-resolve-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-companion-resolve-ffb5beb_tests.cmake")
else()
  add_test(test-companion-resolve_NOT_BUILT-ffb5beb test-companion-resolve_NOT_BUILT-ffb5beb)
endif()
