if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-omnivoice-prompt-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-omnivoice-prompt-ffb5beb_tests.cmake")
else()
  add_test(test-omnivoice-prompt_NOT_BUILT-ffb5beb test-omnivoice-prompt_NOT_BUILT-ffb5beb)
endif()
