if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-no-emotion-recognition-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-no-emotion-recognition-ffb5beb_tests.cmake")
else()
  add_test(test-no-emotion-recognition_NOT_BUILT-ffb5beb test-no-emotion-recognition_NOT_BUILT-ffb5beb)
endif()
