if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-issue-353-split-pipeline-3f719b1_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-issue-353-split-pipeline-3f719b1_tests.cmake")
else()
  add_test(test-issue-353-split-pipeline_NOT_BUILT-3f719b1 test-issue-353-split-pipeline_NOT_BUILT-3f719b1)
endif()
