if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-bench-enabled-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-bench-enabled-ffb5beb_tests.cmake")
else()
  add_test(test-bench-enabled_NOT_BUILT-ffb5beb test-bench-enabled_NOT_BUILT-ffb5beb)
endif()
