if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-m2m100-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-m2m100-params-ffb5beb_tests.cmake")
else()
  add_test(test-m2m100-params_NOT_BUILT-ffb5beb test-m2m100-params_NOT_BUILT-ffb5beb)
endif()
