if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-punctuation-policy-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-punctuation-policy-ffb5beb_tests.cmake")
else()
  add_test(test-punctuation-policy_NOT_BUILT-ffb5beb test-punctuation-policy_NOT_BUILT-ffb5beb)
endif()
