if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-indextts-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-indextts-params-ffb5beb_tests.cmake")
else()
  add_test(test-indextts-params_NOT_BUILT-ffb5beb test-indextts-params_NOT_BUILT-ffb5beb)
endif()
