if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-crispasr-cache-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-crispasr-cache-ffb5beb_tests.cmake")
else()
  add_test(test-crispasr-cache_NOT_BUILT-ffb5beb test-crispasr-cache_NOT_BUILT-ffb5beb)
endif()
