if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-qwen3tts-params-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-qwen3tts-params-ffb5beb_tests.cmake")
else()
  add_test(test-qwen3tts-params_NOT_BUILT-ffb5beb test-qwen3tts-params_NOT_BUILT-ffb5beb)
endif()
