if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-tabcnn-436e84c_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-tabcnn-436e84c_tests.cmake")
else()
  add_test(test-tabcnn_NOT_BUILT-436e84c test-tabcnn_NOT_BUILT-436e84c)
endif()
