if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-uroman-f121995_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-uroman-f121995_tests.cmake")
else()
  add_test(test-uroman_NOT_BUILT-f121995 test-uroman_NOT_BUILT-f121995)
endif()
