add_test( [==[Spanish LTS: ch/ll/rr/ñ]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-g2p-es [==[Spanish LTS: ch/ll/rr/ñ]==] --colour-mode ansi  )
set_tests_properties( [==[Spanish LTS: ch/ll/rr/ñ]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit g2p spanish TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[Spanish LTS: b/d/g lenition]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-g2p-es [==[Spanish LTS: b/d/g lenition]==] --colour-mode ansi  )
set_tests_properties( [==[Spanish LTS: b/d/g lenition]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit g2p spanish TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[Spanish LTS: c/z seseo, g/j jota]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-g2p-es [==[Spanish LTS: c/z seseo\, g/j jota]==] --colour-mode ansi  )
set_tests_properties( [==[Spanish LTS: c/z seseo, g/j jota]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit g2p spanish TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[Spanish LTS: silent h, qu]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-g2p-es [==[Spanish LTS: silent h\, qu]==] --colour-mode ansi  )
set_tests_properties( [==[Spanish LTS: silent h, qu]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit g2p spanish TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[Spanish LTS: vowels and r]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-g2p-es [==[Spanish LTS: vowels and r]==] --colour-mode ansi  )
set_tests_properties( [==[Spanish LTS: vowels and r]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit g2p spanish TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[Spanish text_to_ipa]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-g2p-es [==[Spanish text_to_ipa]==] --colour-mode ansi  )
set_tests_properties( [==[Spanish text_to_ipa]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit g2p spanish TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[es: punctuation is dropped by default, kept on request]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-g2p-es [==[es: punctuation is dropped by default\, kept on request]==] --colour-mode ansi  )
set_tests_properties( [==[es: punctuation is dropped by default, kept on request]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit g2p spanish TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[es: the hyphen is a separator, never a mark]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-g2p-es [==[es: the hyphen is a separator\, never a mark]==] --colour-mode ansi  )
set_tests_properties( [==[es: the hyphen is a separator, never a mark]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit g2p spanish TIMEOUT 30 SKIP_RETURN_CODE 4)
add_test( [==[es: a quoted word is looked up without its quotes]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-g2p-es [==[es: a quoted word is looked up without its quotes]==] --colour-mode ansi  )
set_tests_properties( [==[es: a quoted word is looked up without its quotes]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit g2p spanish TIMEOUT 30 SKIP_RETURN_CODE 4)
set( test-g2p-es_TESTS [==[Spanish LTS: ch/ll/rr/ñ]==] [==[Spanish LTS: b/d/g lenition]==] [==[Spanish LTS: c/z seseo, g/j jota]==] [==[Spanish LTS: silent h, qu]==] [==[Spanish LTS: vowels and r]==] [==[Spanish text_to_ipa]==] [==[es: punctuation is dropped by default, kept on request]==] [==[es: the hyphen is a separator, never a mark]==] [==[es: a quoted word is looked up without its quotes]==])
