if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test_slice_timestamps-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test_slice_timestamps-ffb5beb_tests.cmake")
else()
  add_test(test_slice_timestamps_NOT_BUILT-ffb5beb test_slice_timestamps_NOT_BUILT-ffb5beb)
endif()
