if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-gguf-bounds-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-gguf-bounds-ffb5beb_tests.cmake")
else()
  add_test(test-gguf-bounds_NOT_BUILT-ffb5beb test-gguf-bounds_NOT_BUILT-ffb5beb)
endif()
