if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-core-tts-voice-policy-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-core-tts-voice-policy-ffb5beb_tests.cmake")
else()
  add_test(test-core-tts-voice-policy_NOT_BUILT-ffb5beb test-core-tts-voice-policy_NOT_BUILT-ffb5beb)
endif()
