add_test( [==[math: M_PI is available and accurate]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-math-consistency [==[math: M_PI is available and accurate]==]  )
set_tests_properties( [==[math: M_PI is available and accurate]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit SKIP_RETURN_CODE 4)
add_test( [==[math: common trigonometric functions work]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-math-consistency [==[math: common trigonometric functions work]==]  )
set_tests_properties( [==[math: common trigonometric functions work]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit SKIP_RETURN_CODE 4)
set( test-math-consistency_TESTS [==[math: M_PI is available and accurate]==] [==[math: common trigonometric functions work]==])
