add_test( [==[uroman: ASCII passes through unchanged]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-uroman [==[uroman: ASCII passes through unchanged]==]  )
set_tests_properties( [==[uroman: ASCII passes through unchanged]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit uroman SKIP_RETURN_CODE 4)
add_test( [==[uroman: Arabic consonants romanize]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-uroman [==[uroman: Arabic consonants romanize]==]  )
set_tests_properties( [==[uroman: Arabic consonants romanize]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit uroman SKIP_RETURN_CODE 4)
add_test( [==[uroman: Arabic sentence romanizes]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-uroman [==[uroman: Arabic sentence romanizes]==]  )
set_tests_properties( [==[uroman: Arabic sentence romanizes]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit uroman SKIP_RETURN_CODE 4)
add_test( [==[uroman: Cyrillic romanizes]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-uroman [==[uroman: Cyrillic romanizes]==]  )
set_tests_properties( [==[uroman: Cyrillic romanizes]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit uroman SKIP_RETURN_CODE 4)
add_test( [==[uroman: mixed script preserves spaces]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-uroman [==[uroman: mixed script preserves spaces]==]  )
set_tests_properties( [==[uroman: mixed script preserves spaces]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit uroman SKIP_RETURN_CODE 4)
add_test( [==[uroman: needs_romanization detects Arabic]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-uroman [==[uroman: needs_romanization detects Arabic]==]  )
set_tests_properties( [==[uroman: needs_romanization detects Arabic]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit uroman SKIP_RETURN_CODE 4)
add_test( [==[uroman: needs_romanization detects Cyrillic]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-uroman [==[uroman: needs_romanization detects Cyrillic]==]  )
set_tests_properties( [==[uroman: needs_romanization detects Cyrillic]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit uroman SKIP_RETURN_CODE 4)
add_test( [==[uroman: empty string]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-uroman [==[uroman: empty string]==]  )
set_tests_properties( [==[uroman: empty string]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit uroman SKIP_RETURN_CODE 4)
add_test( [==[uroman: per-word romanization is label-safe (#419)]==] /kaggle/working/CrispASR-NB/t4-kaggle-build/bin/test-uroman [==[uroman: per-word romanization is label-safe (#419)]==]  )
set_tests_properties( [==[uroman: per-word romanization is label-safe (#419)]==] PROPERTIES WORKING_DIRECTORY /kaggle/working/CrispASR-NB/t4-kaggle-build/tests LABELS unit uroman SKIP_RETURN_CODE 4)
set( test-uroman_TESTS [==[uroman: ASCII passes through unchanged]==] [==[uroman: Arabic consonants romanize]==] [==[uroman: Arabic sentence romanizes]==] [==[uroman: Cyrillic romanizes]==] [==[uroman: mixed script preserves spaces]==] [==[uroman: needs_romanization detects Arabic]==] [==[uroman: needs_romanization detects Cyrillic]==] [==[uroman: empty string]==] [==[uroman: per-word romanization is label-safe (#419)]==])
