if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-spectral-diarize-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-spectral-diarize-ffb5beb_tests.cmake")
else()
  add_test(test-spectral-diarize_NOT_BUILT-ffb5beb test-spectral-diarize_NOT_BUILT-ffb5beb)
endif()
