if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-diarize-pyannote-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-diarize-pyannote-ffb5beb_tests.cmake")
else()
  add_test(test-diarize-pyannote_NOT_BUILT-ffb5beb test-diarize-pyannote_NOT_BUILT-ffb5beb)
endif()
