if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-kokoro-g2p-316-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-kokoro-g2p-316-ffb5beb_tests.cmake")
else()
  add_test(test-kokoro-g2p-316_NOT_BUILT-ffb5beb test-kokoro-g2p-316_NOT_BUILT-ffb5beb)
endif()
