if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-campplus-segpool-3c970ca_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-campplus-segpool-3c970ca_tests.cmake")
else()
  add_test(test-campplus-segpool_NOT_BUILT-3c970ca test-campplus-segpool_NOT_BUILT-3c970ca)
endif()
