if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-link-odr-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-link-odr-ffb5beb_tests.cmake")
else()
  add_test(test-link-odr_NOT_BUILT-ffb5beb test-link-odr_NOT_BUILT-ffb5beb)
endif()
