if(EXISTS "/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-core-lang-names-ffb5beb_tests.cmake")
  include("/kaggle/working/CrispASR-NB/t4-kaggle-build/tests/test-core-lang-names-ffb5beb_tests.cmake")
else()
  add_test(test-core-lang-names_NOT_BUILT-ffb5beb test-core-lang-names_NOT_BUILT-ffb5beb)
endif()
